### PR TITLE
Implementation: Delete Shift Functionality

### PR DESCRIPTION
**Pull request by javalosr2004**

### CODE REVIEW

**Comment by bbmcmann** [comment]
delete works good, hitting no on the 'are you sure?' does not close the modal so there is actually no way to close the modal

**Comment by bbmcmann** [comment]
i'll send you details about changes

**Review by bbmcmann — APPROVED** [review]
looks great, works well on my end!

**Review by bbmcmann — APPROVED** [review]

**Review by Ritvik1121 — APPROVED** [review]
Code looks good and everything works on my end. Good job!

**Pull request merged**
