### PR TITLE
added list of Forums

### PR DESCRIPTION
**Pull request by marissadarnell**
using event data from the constants file to set the title and color of each forum
the forums just link to the same page (Discussion) for now

### CODE REVIEW

**Review by ctperry0301 — CHANGES_REQUESTED** [review]
Looks really good overall. One small thing I noticed is that we get the following warning message in the chrome console when the discussion page is clicked. "Warning: Each child in a list should have a unique "key" prop." It would be great if you could fix this really quick, re-request review, and then this should be good to get this merged in!

**Comment by marissadarnell** [comment]
@ctperry0301 I fixed the warnings you mentioned. 
I was also wondering, should I move my styled components to the styled-components folder?

**Comment by ctperry0301** [comment]
> @ctperry0301 I fixed the warnings you mentioned.
> I was also wondering, should I move my styled components to the styled-components folder?

@marissadarnell the styled-components folder is mostly for styles that would be used in more than one place in the app. So probably not for this weeks work, as I think most of the styles will just exist here.

**Review by ctperry0301 — APPROVED** [review]
Looks great. Thanks Marissa!

**Pull request merged**
