### PR TITLE
Dev 8 make styles uniform

### PR DESCRIPTION
**Pull request by ctperry0301**
@bbmcmann Please Review the signup page when you get a chance.
@marissadarnell Please Review the login page when you get a chance.
@jlu51 Please Review the Reset Password page when you get a chance.
@n0ximus Please Review the Success Page when you get a chance.

### CODE REVIEW

**Review by jlu51 — APPROVED** [review]
Thank you for fixing up my styling!

Update: Did not catch this upon first look, but noticed that the button on the reset password page is named incorrectly as it says "Create Account" when it should be "Confirm."

Screen Shot 2021-01-26 at 12 43 09 PM

**Review by jlu51 — APPROVED** [review]

**Review by marissadarnell — COMMENTED** [review]
Nice job! It looks really good. I'm not sure if it matters, but there's a point where the Create Account button stacks text. It goes away if you decrease the StyledCol padding to 8-9%.
Otherwise it's really clean :)

image

**Review by bbmcmann — APPROVED** [review]
Looks really good to me, everything worked well when I tested it too. Thanks for fixing my component styles!

**Comment by ctperry0301** [comment]
> Nice job! It looks really good. I'm not sure if it matters, but there's a point where the Create Account button stacks text. It goes away if you decrease the StyledCol padding to 8-9%.
> Otherwise it's really clean :)
> 
> image

Great catch. Fixed!

**Comment by ctperry0301** [comment]
> Thank you for fixing up my styling!
> 
> Update: Did not catch this upon first look, but noticed that the button on the reset password page is named incorrectly as it says "Create Account" when it should be "Confirm."
> 
> Screen Shot 2021-01-26 at 12 43 09 PM

Great catch, Fixed now.

**Review by n0ximus — APPROVED** [review]
I just checked the confirmation pages. It looks perfect. However, should we be concerned about zooming in/out on desktop? When I zoom out, everything changes in size except the confirmation image icon.

**Comment by ctperry0301** [comment]
> I just checked the confirmation pages. It looks perfect. However, should we be concerned about zooming in/out on desktop? When I zoom out, everything changes in size except the confirmation image icon.

Thanks for spotting that. I dont think we will need to worry about that, however, I'll run it by Mandy to confirm that.

**Pull request merged**
