### PR TITLE
Validate selected times are within vigil times

### PR DESCRIPTION
**Pull request by bbmcmann**
users are unable to signup for shifts outside of scheduled vigil times. They will be prompted with a corresponding error message notifying them of the needed change.

### CODE REVIEW

**Review by ctperry0301 — CHANGES_REQUESTED** [review]
Looks really good overall. One small thing I noticed is that there is no validation to check if the entered end date comes before the vigil ends. Go ahead and add that, and it should be good to be merged in!

Also I went ahead and changed a few of the messages text, so you might need to pull from this branch to get the most recent changes.

**Comment by bbmcmann** [comment]
Alright, I went ahead and added the extra validation, let me know if any more changes are needed!

**Comment by ctperry0301** [comment]
This picture represents a shift that somebody should be able to sign up for, however the validation is saying that is is not allowed. After this is fixed, I think it should be perfect. (lmk if you need any clarification about this issue)

Screen Shot 2021-05-17 at 9 21 11 PM

**Review by ctperry0301 — CHANGES_REQUESTED** [review]
See above comment ^

**Comment by bbmcmann** [comment]
I went back and fixed the multi day error. I finally found a way easier way to compare dates so I just refactored the old code. We were missing validation to make sure the selected dates were within the vigil date range so I added that as well.

**Review by ctperry0301 — APPROVED** [review]
I get this issue if I try to click on a vigil that is a single day vigil. 

Screen Shot 2021-05-18 at 3 36 26 PM

**Review by ctperry0301 — CHANGES_REQUESTED** [review]
See above ^^

**Comment by bbmcmann** [comment]
That's my bad, deleted the wrong if statement while cleaning up. I just tested this and it should work now

**Review by ctperry0301 — CHANGES_REQUESTED** [review]
See the below screenshot for the only other bug I found. It is throwing an error on a completely during a completely valid date (Im pretty sure this will be the last fix)

Screen Shot 2021-05-18 at 4 22 56 PM

**Comment by bbmcmann** [comment]
Did you input in a certain order? I'm not able to recreate the bug

**Comment by bbmcmann** [comment]
I added some extra logic to make sure I wasn't making a reference valid when it was previously invalid in the function. So everything should work included the inverted dates check

**Review by ctperry0301 — APPROVED** [review]
Works Perfect now! Thanks for responding to the requested changes quickly and it looks/works great!

**Pull request merged**
