### PR TITLE
Converted all pages to new vigil data format

### PR DESCRIPTION
**Pull request by vwinstea**
I converted all of the schedule related pages to the new format we are using for vigils. I ended up not using the datetime selector since it doesn't look like it has mobile support, but other than that everything should be up to spec.

### CODE REVIEW

**Review by jlu51 — CHANGES_REQUESTED** [review]
Everything looks good except when accessing the History page, it prompts this undefined  error.

"Cannot read property 'shiftStartTime' of undefined"

Could be that you have forgotten to reflect the the backend Vigil structure changes in History component. Everything else that I looked at is good!

**Comment by vwinstea** [comment]
I tried recreating that issue on my account and I couldn't do it since I'm currently not signed up for any shifts. I think the issue is that I deleted the vigil that is associated with your shifts, but your shifts weren't deleted in the prevShifts array. Also, the shift sign up doesn't fully work right now because it will create a shift in the vigils collection, but the shift won't be added to the prevShift array in the users collection, so I couldn't test out this functionality even if I wanted to.

For now I think this behavior is fine and you might want to manually delete your shifts from the prevShifts array. However, @ctperry0301 should probably know about this issue since I'm not sure what the expected behavior should be.

**Review by ctperry0301 — APPROVED** [review]
This code is actually really impressive! Great work and thanks for stepping up and doing this (somewhat tedious) task

**Review by jlu51 — APPROVED** [review]

**Comment by ctperry0301** [comment]
> I tried recreating that issue on my account and I couldn't do it since I'm currently not signed up for any shifts. I think the issue is that I deleted the vigil that is associated with your shifts, but your shifts weren't deleted in the prevShifts array. Also, the shift sign up doesn't fully work right now because it will create a shift in the vigils collection, but the shift won't be added to the prevShift array in the users collection, so I couldn't test out this functionality even if I wanted to.
> 
> For now I think this behavior is fine and you might want to manually delete your shifts from the prevShifts array. However, @ctperry0301 should probably know about this issue since I'm not sure what the expected behavior should be.

Great catch both @jlu51 and @vwinstea. The "shift won't be added to the prevShift array in the users collection" is a pretty large bug that we will need to address sometime in the following few weeks.

**Pull request merged**
